# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_add_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
