# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(9)])),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_booking',
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('date', 'hour')]),
        ),
    ]
