# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:41
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 9, 11, 9, 40, 57, 177414)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(9)]),
            preserve_default=False,
        ),
    ]
