# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_add_date_and_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'hour']},
        ),
    ]
